const SOCKETEVENT = Object.freeze({

    GROUP_ADMIN: 1,
    GROUP_MEMBER: 2,

    SOCKET_REQUEST: "req",
    SOCKET_RESPONSE: "res",

    SEND_NEW_MESSAGE: "SNM",
    SEND_NEW_MESSAGE_RESPONSE: "SNMR",

    CREATE_NEW_GROUP: "CNG",
    CREATE_NEW_GROUP_RESPONSE: "CNGR",

    CHAT_CONVERSTAION_LIST: "CCL",
    CHAT_CONVERSTAION_LIST_RESPONSE: "CCLR",

    JOIN_GROUP: "JG",
    JOIN_GROUP_RESPONSE: "JGR",


})


export {
    SOCKETEVENT
}